# Basic Information 
title: D/DOAN
position: finance
email: dom

# Search Engine Optimization (SEO)
keywords: finance, fintech, design, digital arts, D/DOAN
description: Personal homepage and portfolio of D/DOAN.
canonical: https://domdoes.github.io/

# Links (Update with your actual profile links or delete the lines you don't need)
github_link: https://github.com/domdoes
linkedin: https://www.linkedin.com/in/domdoan/
# twitter: https://twitter.com/

# Images 
# Upload your profile picture to the assets/img folder and ensure the name matches below.
avatar: ./assets/img/me_but_professional.png
favicon: ./assets/img/favicon.png
favicon_dark: ./assets/img/favicon-dark.png

# Font
font: "Sans Serif" 
